// <auto-generated />
using MTstat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTstat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710145338_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MTstat.Models.PlayerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Battles")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "battles");

                    b.Property<int>("DamageDealt")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "damage_dealt");

                    b.Property<int>("HitsPercents")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "hits_percents");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "losses");

                    b.Property<int>("SurvivedBattles")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "survived_battles");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "wins");

                    b.HasKey("Id");

                    b.ToTable("PlayerStats");
                });
#pragma warning restore 612, 618
        }
    }
}
